<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Model\" />
    <None Remove="Database\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Model\" />
    <Folder Include="Database\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.0" />
  </ItemGroup>
</Project>
